name: "Update Configuration and Build"

on:
  workflow_dispatch:
  push:

jobs:
  update-manifest:
    name: "Update Configuration & Build"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      # TO BE DELETED, ONLY TESTING
      - uses: actions/checkout@v5
        with:
          repository: ubiquity-os/plugin-sdk
          ref: feat/config
          path: plugin-sdk
      - name: Build SDK
        run: |
          cd plugin-sdk
          bun install
          bun run sdk:build
          bun pack
          bun add ./plugin-sdk/plugin-sdk-v*.tgz

      - name: Update Manifest and Commit Changes
        uses: ubiquity-os/action-deploy-plugin@main
        with:
          treatAsEsm: true
          sourcemap: false
          pluginEntry: ${{ github.workspace }}/src/functions/http-trigger.ts
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
